# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  coverity:
    name: Coverity
    runs-on: ['self-hosted', 'linux']
    env:
      COVERITY_HOSTNAME: coverity.cls.eng.netapp.com
      COVERITY_PORT: 9090
      COVERITY_USER: sample_committer
      COVERITY_PASSWORD: sample1234
      COVERITY_STREAM: HelloWorld_C++
      CONFIG_FILE: coverityconfig/coverity_config.xml
      INTERMEDIATE_DIR: CoverityIDIR
      ANALYSIS_TOOLS_BIN: /x/eng/coverity/ANALYSIS_TOOLS/2021.03/cov-analysis-linux64-2021.03/bin
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Validate
        run: pwd; tree
        
      - run: ls ${{ env.ANALYSIS_TOOLS_BIN }}
        shell: bash
        
      - run: ${{ env.ANALYSIS_TOOLS_BIN }}/cov-configure --config ${{ env.CONFIG_FILE }} --gcc
        shell: bash
        
      - run: ${{ env.ANALYSIS_TOOLS_BIN }}/cov-build --dir ${{ env.INTERMEDIATE_DIR }} --config ${{ env.CONFIG_FILE }}  g++ hello.cpp -o hello
        shell: bash
        
      - run: ${{ env.ANALYSIS_TOOLS_BIN }}/cov-analyze --dir ${{ env.INTERMEDIATE_DIR }} --strip-path ${{ env.GITHUB_WORKSPACE }} --all
        shell: bash
        
      - run: ${{ env.ANALYSIS_TOOLS_BIN }}/cov-commit-defects --dir ${{ env.INTERMEDIATE_DIR }} --host ${{ env.COVERITY_HOSTNAME }} --dataport ${{ env.COVERITY_PORT }} --user ${{ env.COVERITY_USER }} --password ${{ env.COVERITY_PASSWORD }} --certs /u/khanht/cert.pem --stream ${{ env.COVERITY_STREAM }}
        shell: bash

    
  
